<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\BrandProduk;

class BrandProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['title_brand_produk' => 'ACNES'],
            ['title_brand_produk' => 'ACNOL'],
            ['title_brand_produk' => 'ADARA'],
            ['title_brand_produk' => 'ADEENA'],
            ['title_brand_produk' => 'AIKO COSMETICS'],
            ['title_brand_produk' => 'AIZEN'],
            ['title_brand_produk' => 'AKNEMA'],
            ['title_brand_produk' => 'ALL GLOWS'], 
            ['title_brand_produk' => 'ALLURA'],
            ['title_brand_produk' => 'AMARA KIDS'],
            ['title_brand_produk' => 'AMARANTHINE'],
            ['title_brand_produk' => 'AMPULOGY'],
            ['title_brand_produk' => 'ANIMATE'],
            ['title_brand_produk' => 'A-TRUE'],
            ['title_brand_produk' => 'AVOSKIN'],
            ['title_brand_produk' => 'AXIS-Y'],
            ['title_brand_produk' => 'AYSI'],
            ['title_brand_produk' => 'AZARINE'],
            ['title_brand_produk' => 'AZRINA'],

            ['title_brand_produk' => 'BABY PINK'],
            ['title_brand_produk' => 'BARENBLISS'],
            ['title_brand_produk' => 'BASE'],
            ['title_brand_produk' => 'BEAUDELAB'],
            ['title_brand_produk' => 'BEAUSTA'],
            ['title_brand_produk' => 'BEAUTIES'],
            ['title_brand_produk' => 'BEAUTY ITEMS'],
            ['title_brand_produk' => 'BEBESUP'],
            ['title_brand_produk' => 'BELLFLOWER'],
            ['title_brand_produk' => 'BHUMI'],
            ['title_brand_produk' => 'BIES'],
            ['title_brand_produk' => 'BIOAQUA'],
            ['title_brand_produk' => 'BIO BEAUTY LAB'],
            ['title_brand_produk' => 'BIODERMA'],

            ['title_brand_produk' => 'CARESO'],
            ['title_brand_produk' => 'CBD PRO'],            
            ['title_brand_produk' => 'CESSA'],            
            ['title_brand_produk' => 'CETAPHIL'],            
            ['title_brand_produk' => 'CHAIZA'],            
            ['title_brand_produk' => 'CHELVY'],            
            ['title_brand_produk' => 'CLAY BOTANICALS'],            
            ['title_brand_produk' => 'CLEAN FACE'],            
            ['title_brand_produk' => 'CLEORA'],            
            ['title_brand_produk' => 'COCOFILM'],            
            ['title_brand_produk' => 'CORINE DE FARME'],

            ['title_brand_produk' => 'DAZZLE ME'],
            ['title_brand_produk' => 'DEARME'],            
            ['title_brand_produk' => 'DEAR ME BEAUTY'],            
            ['title_brand_produk' => 'DEAR UP'],            
            ['title_brand_produk' => 'DERMALUZ'],            
            ['title_brand_produk' => 'DEW IT'],            
            ['title_brand_produk' => 'DEWYCEL'],            
            ['title_brand_produk' => 'DOODLE'],            
            ['title_brand_produk' => 'DORSKIN'],            
            ['title_brand_produk' => 'DR+EAM'],

            ['title_brand_produk' => 'EMINA'],
            ['title_brand_produk' => 'ENVYGREEN'],            
            ['title_brand_produk' => 'ERHA'],            
            ['title_brand_produk' => 'ERTO’S'],            
            ['title_brand_produk' => 'ESSCENTIALS'],            
            ['title_brand_produk' => 'ETUDE HOUSE'],            
            ['title_brand_produk' => 'EVERFIT'],            
            ['title_brand_produk' => 'EVERPURE'],            
            ['title_brand_produk' => 'EVERSHINE'],            
            ['title_brand_produk' => 'EVERWHITE'],            
            ['title_brand_produk' => 'EVIAN'],            
            ['title_brand_produk' => 'EZE NAILS'],

            ['title_brand_produk' => 'FABIL'],
            ['title_brand_produk' => 'FACE REPUBLIC'],            
            ['title_brand_produk' => 'FACETOLOGY'],            
            ['title_brand_produk' => 'FARMSKIN'],            
            ['title_brand_produk' => 'FEAT FOR SKIN'],            
            ['title_brand_produk' => 'FOCALLURE'],            
            ['title_brand_produk' => 'FORENCOS'],            
            ['title_brand_produk' => 'FOR SKIN’S SAKE'],            
            ['title_brand_produk' => 'FREEMAN'],            
            ['title_brand_produk' => 'FUKU SKIN'],

            ['title_brand_produk' => 'GEA'],
            ['title_brand_produk' => 'GENTLE HOUR'],            
            ['title_brand_produk' => 'GIRLPAL'],            
            ['title_brand_produk' => 'GLAMERS'],            
            ['title_brand_produk' => 'GLAMFIX'],            
            ['title_brand_produk' => 'GLOW BETTER'],            
            ['title_brand_produk' => 'GLOWLABS'],            
            ['title_brand_produk' => 'GLOWPEDIA'],            
            ['title_brand_produk' => 'GLUTANEX'],            
            ['title_brand_produk' => 'GOBAN COSMETICS'],            
            ['title_brand_produk' => 'GOLDEN BEAR'],            
            ['title_brand_produk' => 'GOLDEN VIERA'],            
            ['title_brand_produk' => 'GONGBEE'],            
            ['title_brand_produk' => 'GORJES'],            
            ['title_brand_produk' => 'GRACE & GLOW'],            
            ['title_brand_produk' => 'GRAFEN'],

            ['title_brand_produk' => 'HADA LABO'],
            ['title_brand_produk' => 'HAIRMONY'],            
            ['title_brand_produk' => 'HALE'],            
            ['title_brand_produk' => 'HANABO'],            
            ['title_brand_produk' => 'HANASUI'],            
            ['title_brand_produk' => 'HANSKIN'],            
            ['title_brand_produk' => 'HATOMUGI'],            
            ['title_brand_produk' => 'HAYEJIN'],            
            ['title_brand_produk' => 'HAZELINE'],            
            ['title_brand_produk' => 'HEIMISH'],            
            ['title_brand_produk' => 'HERBI GLOW'],            
            ['title_brand_produk' => 'HERBORIST'],            
            ['title_brand_produk' => 'HISTOIRE NATURELLE'],            
            ['title_brand_produk' => 'HOLIKA HOLIKA'],            
            ['title_brand_produk' => 'HUMPHREY'],

            ['title_brand_produk' => 'IKIGAI'],
            ['title_brand_produk' => 'ILIKEMYSELF'],            
            ['title_brand_produk' => 'IMPLORA'],            
            ['title_brand_produk' => 'INDOGANIC'],            
            ['title_brand_produk' => 'INGRID'],            
            ['title_brand_produk' => 'INNISFREE'],            
            ['title_brand_produk' => 'IFTER'],            
            ['title_brand_produk' => 'I TRUST NATURE'],            
            ['title_brand_produk' => 'IUNIK'],

            ['title_brand_produk' => 'JACQUELLE'],
            ['title_brand_produk' => 'JAGIYA'],            
            ['title_brand_produk' => 'JARKEEN'],            
            ['title_brand_produk' => 'JARTE BEAUTY'],            
            ['title_brand_produk' => 'JIERA'],            
            ['title_brand_produk' => 'JIWOONE'],            
            ['title_brand_produk' => 'JOSELIN'],            
            ['title_brand_produk' => 'JOYLAB'],            
            ['title_brand_produk' => 'JUJU & CO'],            
            ['title_brand_produk' => 'JVR'],        
        
            ['title_brand_produk' => 'KAHF'],
            ['title_brand_produk' => 'KAILA'],            
            ['title_brand_produk' => 'KANNA'],            
            ['title_brand_produk' => 'KELAYA'],            
            ['title_brand_produk' => 'KEY BY SA'],            
            ['title_brand_produk' => 'KHALISA'],            
            ['title_brand_produk' => 'KIMUSE'],            
            ['title_brand_produk' => 'KINDY GLOW'],            
            ['title_brand_produk' => 'KINOHIMITSU'],            
            ['title_brand_produk' => 'KLAIRS'],            
            ['title_brand_produk' => 'KLEVERU'],            
            ['title_brand_produk' => 'KOPLINA'],            
            ['title_brand_produk' => 'KOSE COSMEPORT'],            
            ['title_brand_produk' => 'KOTTONVILLE'],            
            ['title_brand_produk' => 'KRAVE'],            
            ['title_brand_produk' => 'KUKUI'],            
            ['title_brand_produk' => 'KUTUS KUTUS'],            
            ['title_brand_produk' => 'KYND BEAUTY'],            
            ['title_brand_produk' => 'KYORO'],      
            
            ['title_brand_produk' => 'LABORE'],
            ['title_brand_produk' => 'LACOCO'],            
            ['title_brand_produk' => 'LAE SA LUAY'],            
            ['title_brand_produk' => 'LALABEE'],            
            ['title_brand_produk' => 'LA TULIPE'],            
            ['title_brand_produk' => 'LAVIE LASH'],            
            ['title_brand_produk' => 'LAVOJOY'],            
            ['title_brand_produk' => 'LEAN LAB'],            
            ['title_brand_produk' => 'LIPLAPIN'],            
            ['title_brand_produk' => 'LOOKE'],            
            ['title_brand_produk' => 'LOOLOO'],            
            ['title_brand_produk' => 'L’OREAL'],            
            ['title_brand_produk' => 'LOVE BEAUTY AND PLANET'],            
            ['title_brand_produk' => 'LT PRO'],            
            ['title_brand_produk' => 'LUXCRIME'],    
            
            ['title_brand_produk' => 'MADAM GIE'],
            ['title_brand_produk' => 'MAD FOR MAKEUP'],            
            ['title_brand_produk' => 'MAKARIZO'],            
            ['title_brand_produk' => 'MAKE OVER'],            
            ['title_brand_produk' => 'MARY & CO'],            
            ['title_brand_produk' => 'MASKA.LAB'],            
            ['title_brand_produk' => 'MAXCLINIC'],            
            ['title_brand_produk' => 'MAYBELLINE'],            
            ['title_brand_produk' => 'MIBELLE'],            
            ['title_brand_produk' => 'MINERAL BOTANICA'],            
            ['title_brand_produk' => 'MIRAEL'],            
            ['title_brand_produk' => 'MIRANDA'],            
            ['title_brand_produk' => 'MIRELLE'],            
            ['title_brand_produk' => 'MISSHA'],            
            ['title_brand_produk' => 'MISS ROSE'],            
            ['title_brand_produk' => 'MISS U2'],            
            ['title_brand_produk' => 'MOIST DIANE'],            
            ['title_brand_produk' => 'MORR'],            
            ['title_brand_produk' => 'MUSTIKA RATU'],            
            ['title_brand_produk' => 'MY SKIN HER'],   
            
            ['title_brand_produk' => 'NACIFIC'],
            ['title_brand_produk' => 'NADFASKIN'],            
            ['title_brand_produk' => 'NAMA'],            
            ['title_brand_produk' => 'NATRA BIO'],            
            ['title_brand_produk' => 'NATROL'],            
            ['title_brand_produk' => 'NATUR BEAUTY'],            
            ['title_brand_produk' => 'NATURE’S HEALTH'],            
            ['title_brand_produk' => 'NELSONS'],            
            ['title_brand_produk' => 'NEOGEN'],            
            ['title_brand_produk' => 'NEW CELL'],            
            ['title_brand_produk' => 'NOBB'],            
            ['title_brand_produk' => 'NOERA'],            
            ['title_brand_produk' => 'NOOLAB'],            
            ['title_brand_produk' => 'NOVO'],            
            ['title_brand_produk' => 'N’PURE'],            
            ['title_brand_produk' => 'NUFACE'],            
            ['title_brand_produk' => 'NUSANTICS'],            
            ['title_brand_produk' => 'NUTRIA BIOTECH'],            
            ['title_brand_produk' => 'NUTRISHE'],    
            
            ['title_brand_produk' => 'OASEA'],
            ['title_brand_produk' => 'OH K!'],            
            ['title_brand_produk' => 'OHMYSKIN'],            
            ['title_brand_produk' => 'OMG'],            
            ['title_brand_produk' => 'OMNISKIN'],            
            ['title_brand_produk' => 'ONE THING'],            
            ['title_brand_produk' => 'ONYX'],            
            ['title_brand_produk' => 'OTHERS'],            
            ['title_brand_produk' => 'O TWO O'],            
            ['title_brand_produk' => 'OXY'],            
            ['title_brand_produk' => 'OYASUMI'],     
            
            ['title_brand_produk' => 'PEARL & DARLING'],
            ['title_brand_produk' => 'PERFECT LAB'],            
            ['title_brand_produk' => 'PERIPERA'],            
            ['title_brand_produk' => 'PIGEON TEENS'],            
            ['title_brand_produk' => 'PINKBERRY'],            
            ['title_brand_produk' => 'PINKFLASH'],            
            ['title_brand_produk' => 'PINKROULETTE'],            
            ['title_brand_produk' => 'PIXY'],            
            ['title_brand_produk' => 'PORTIA SKIN'],            
            ['title_brand_produk' => 'POWDER STORY'],            
            ['title_brand_produk' => 'PRATISTA'],            
            ['title_brand_produk' => 'PRECIOUS SKIN'],            
            ['title_brand_produk' => 'PREMIERE BEAUTY'],            
            ['title_brand_produk' => 'PRISA'],            
            ['title_brand_produk' => 'PROSPERO'],            
            ['title_brand_produk' => 'PURBASARI'],            
            ['title_brand_produk' => 'PURESSENTIEL'],            
            ['title_brand_produk' => 'PURIVERA'],            
            ['title_brand_produk' => 'PURNAMA BEAUTY'],      
            
            ['title_brand_produk' => 'RABBIT HABIT'],
            ['title_brand_produk' => 'RADI SKIN'],            
            ['title_brand_produk' => 'RAECCA'],            
            ['title_brand_produk' => 'RAYOU'],            
            ['title_brand_produk' => 'RDL'],            
            ['title_brand_produk' => 'REAL WHITE'],            
            ['title_brand_produk' => 'REE DERMA'],            
            ['title_brand_produk' => 'REI SKIN'],            
            ['title_brand_produk' => 'REJUV'],            
            ['title_brand_produk' => 'RESET THE SKIN'],            
            ['title_brand_produk' => 'RHENZA'],            
            ['title_brand_produk' => 'RIADY BY IRWAN'],            
            ['title_brand_produk' => 'RIVERA'],            
            ['title_brand_produk' => 'ROCEO'],            
            ['title_brand_produk' => 'ROSE ALL DAY'],            
            ['title_brand_produk' => 'ROSSA BEAUTY'],            
            ['title_brand_produk' => 'ROUNDLAB'],

            ['title_brand_produk' => 'SACE LADY'],
            ['title_brand_produk' => 'SADA BY CATHY SHARON'],            
            ['title_brand_produk' => 'SAFI'],            
            ['title_brand_produk' => 'SANIYE'],            
            ['title_brand_produk' => 'SATELLITE OF GLOW'],            
            ['title_brand_produk' => 'SATURDAY LOOKS'],            
            ['title_brand_produk' => 'SBCSKIN'],            
            ['title_brand_produk' => 'SCARLETT'],            
            ['title_brand_produk' => 'SECA'],            
            ['title_brand_produk' => 'SECONDATE'],            
            ['title_brand_produk' => 'SELSUN'],            
            ['title_brand_produk' => 'SHERIZ'],            
            ['title_brand_produk' => 'SIMPLYSITI'],            
            ['title_brand_produk' => 'SKIN 1004'],            
            ['title_brand_produk' => 'SKIN AQUA'],            
            ['title_brand_produk' => 'SKINAUTHENTHIC'],            
            ['title_brand_produk' => 'SKINMEE'],            
            ['title_brand_produk' => 'SKINMISO'],            
            ['title_brand_produk' => 'SKINOURU'],            
            ['title_brand_produk' => 'SKINSPACE'],            
            ['title_brand_produk' => 'SKINSTER'],            
            ['title_brand_produk' => 'SKIN THEORY'],            
            ['title_brand_produk' => 'SKINTIFIC'],            
            ['title_brand_produk' => 'SKIN TIME'],            
            ['title_brand_produk' => 'SOME BY MI'],            
            ['title_brand_produk' => 'SORCHA'],            
            ['title_brand_produk' => 'STUDIO TROPIK'],            
            ['title_brand_produk' => 'SUDOCREAM'],            
            ['title_brand_produk' => 'SUGARPOT'],            
            ['title_brand_produk' => 'SYB'],            
            ['title_brand_produk' => 'SYCA'],        

            ['title_brand_produk' => 'TAVAS'],
            ['title_brand_produk' => 'TEDDY CLUBS'],            
            ['title_brand_produk' => 'TERATU BEAUTY'],            
            ['title_brand_produk' => 'TERRA NATURA'],            
            ['title_brand_produk' => 'THE AUBREE'],            
            ['title_brand_produk' => 'THE BATH BOX'],            
            ['title_brand_produk' => 'THE BODY SHOP'],            
            ['title_brand_produk' => 'TIGA LAB'],            
            ['title_brand_produk' => 'TOGI JIRU'],            
            ['title_brand_produk' => 'TONE'],            
            ['title_brand_produk' => 'TROPE BEBE'],            
            ['title_brand_produk' => 'TRUE TO SKIN'],            
            ['title_brand_produk' => 'TRUEVE'],

            ['title_brand_produk' => 'USTRAA'],

            ['title_brand_produk' => 'VICTORIA'],
            ['title_brand_produk' => 'VIP COLLAGEN'],            
            ['title_brand_produk' => 'VOTRE PEAU'],

            ['title_brand_produk' => 'WARDAH'],
            ['title_brand_produk' => 'W DRESSROOM'],            
            ['title_brand_produk' => 'WELLNESS'],            
            ['title_brand_produk' => 'WESTCARE'],            
            ['title_brand_produk' => 'WHITE DIARY'],            
            ['title_brand_produk' => 'WHITELAB'],            
            ['title_brand_produk' => 'WHITE STORY'],            
            ['title_brand_produk' => 'WITH ME'],            
            ['title_brand_produk' => 'WMU'],            
            ['title_brand_produk' => 'WONDERLY'],            
            ['title_brand_produk' => 'WONJIN'],

            ['title_brand_produk' => 'YONIN'],
            ['title_brand_produk' => 'YOONA'],            
            ['title_brand_produk' => 'Y.O.U'],            
            ['title_brand_produk' => 'YOUVIT'],            
            
            ['title_brand_produk' => 'ZLOTA'],        
        ];

        BrandProduk::insert($data);

    }
}
